# Generated by Django 2.1.5 on 2019-01-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iHub_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='full',
            field=models.BooleanField(default=False, verbose_name='是否人数已满'),
        ),
    ]
