# Generated by Django 2.1.5 on 2019-02-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iHub_site', '0003_auto_20190130_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='当前是否未营业'),
        ),
    ]
